# Basic setup
owner: chaotic-aur
repo: chaotic-uptimes
assignees:
  - dr460nf1r3
  - JustTNE

# Our mirrors
sites:
  - name: Homepage
    url: https://aur.chaotic.cx
  - name: The router
    url: https://geo-mirror.chaotic.cx
  - name: cdn (Cloudflare R2)
    url: https://cdn-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
  - name: bg (Sudoman)
    url: https://shantitribe.eu
    assignees:
      - thotypous
  - name: br (UFSCar Alcateia)
    url: mirror.ufscar.br
    assignees:
      - thotypous
  - name: ca (freebird54)
    url: https://birdrepo.ddns.net
  - name: cdn-cn (Aliyun)
    url: https://cdn-cn-mirror.chaotic.cx/
  - name: cl (jkcgs)
    url: https://mirror.owo.cl
    assignees:
      - jkcgs
  - name: de-2 (Bangl)
    url: https://chaotic.bangl.de
  - name: de-3 (itsTyrion)
    url: https://v.itstyrion.de
    assignees:
      - itsTyrion
  - name: de-4 (redglobuli)
    url: https://chaotic.pl4ygr0und.de
    assignees:
      - redglobuli
  - name: es (JKA Network)
    url: https://repo.jkanetwork.com
  - name: es-2 (Ícar)
    url: https://chaotic.icarns.xyz
    assignees:
      - juxuanu
  - name: es-4 (Ícar)
    url: https://chaotic-2.icarns.xyz
    assignees:
      - juxuanu
  - name: gr (vmmaniac)
    url: https://mirrors.sytes.net
    assignees:
      - vmmaniac
  - name: in (Naman)
    url: https://in-mirror.garudalinux.org
    assignees:
      - Namanlp
  - name: in-2 (Albony)
    url: https://mirror.albony.xyz
    assignees:
      - Albonycal
  - name: in-4 (Albony)
    url: http://mirror.maa.albony.in
    assignees:
      - Albonycal
  - name: kr (silent-heigou)
    url: https://mirror.heigou.pe.kr
    assignees:
      - silent-heigou
  - name: secret (Garuda)
    url: https://builds.garudalinux.org
  - name: sg (Freedif)
    url: https://mirror.freedif.org
    assignees:
      - KaribuTW
  - name: us-mi (Technetium1)
    url: https://chaoticmirror.com
    assignees:
      - Technetium1
  - name: us-tx (xstefen)
    url: https://chaotic.xstefen.dev
    assignees:
      - xstefen
  - name: us-ut (Ash)
    url: https://mirror.theash.xyz
    assignees:
      - the-ashh

# Theming of the statuspage
status-website:
  baseUrl: /
  cname: uptimes.chaotic.cx
  introMessage: This is the status page of Chaotic-AUR which shows current uptime status and historic data 🕵🏻‍♀️
  introTitle: Want to know which mirrors are up?
  logoUrl: https://avatars.githubusercontent.com/u/66071775?s=400&u=99bc0536e7e77fe3e58839996600848f2d930ed5&v=4
  name: Chaotic-AUR Uptimes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://aur.chaotic.cx
  theme: night
  singleCommit: true

# Configuration of the bots commits
commitMessages:
  commitAuthorName: "Chaotic Temeraire"
  commitAuthorEmail: "actions@chaotic.cx"

# Recommended for GitHub API to work
user-agent: chaotic-aur

workflowSchedule:
  uptime: "0 0 1 1 *"
