# Basic setup
owner: chaotic-aur
repo: chaotic-uptimes
assignees:
  - dr460nf1r3
  - JustTNE

# Our mirrors
sites:
  - name: Homepage
    maxResponseTime: 120000
    url: https://aur.chaotic.cx
  - name: The router
    maxResponseTime: 120000
    url: https://geo-mirror.chaotic.cx
  - name: cdn (Cloudflare R2)
    maxResponseTime: 120000
    url: https://cdn-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
  - name: bg (Sudoman)
    maxResponseTime: 120000
    url: https://bg-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - thotypous
  - name: br (UFSCar Alcateia)
    maxResponseTime: 120000
    url: https://br-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - thotypous
  - name: br-2 (Alisson)
    maxResponseTime: 120000
    url: https://br-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - alissonlauffer
  - name: ca (freebird54)
    maxResponseTime: 120000
    url: https://ca-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
  - name: cdn-cn (Aliyun)
    maxResponseTime: 120000
    url: https://cdn-cn-mirror.chaotic.cx/
  - name: cl (jkcgs)
    maxResponseTime: 120000
    url: https://cl-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - jkcgs
  - name: de (dr460nf1r3)
    maxResponseTime: 120000
    url: https://de-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - dr460nf1r3
  - name: de-2 (Bangl)
    maxResponseTime: 120000
    url: https://de-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
  - name: de-3 (itsTyrion)
    maxResponseTime: 120000
    url: https://de-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - itsTyrion
  - name: de-4 (redglobuli)
    maxResponseTime: 120000
    url: https://de-4-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - redglobuli
  - name: es (JKA Network)
    url: https://es-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
  - name: es-2 (Ícar)
    maxResponseTime: 120000
    url: https://es-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - juxuanu
  - name: fr (Snowy)
    maxResponseTime: 120000
    url: https://fr-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - Gontier-Julien
  - name: gr (vmmaniac)
    maxResponseTime: 120000
    url: https://gr-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - vmmaniac
  - name: in (Naman)
    maxResponseTime: 120000
    url: https://in-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - Namanlp
  - name: in-2 (Albony)
    maxResponseTime: 120000
    url: https://in-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - Albonycal
  - name: kr (silent-heigou)
    maxResponseTime: 120000
    url: https://kr-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - silent-heigou
  - name: secret (Garuda)
    maxResponseTime: 120000
    url: https://secret-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
  - name: sg (Freedif)
    maxResponseTime: 120000
    url: https://sg-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - KaribuTW
  - name: us-fl (Alisson)
    maxResponseTime: 120000
    url: https://us-fl-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - alissonlauffer
  - name: us-mi (Technetium1)
    maxResponseTime: 120000
    url: https://us-mi-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - Technetium1
  - name: us-ny (Zoe)
    url: https://us-ny-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - zoeruda
  - name: us-tx (xstefen)
    maxResponseTime: 120000
    url: https://us-tx-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - xstefen
  - name: us-ut (Ash)
    maxResponseTime: 120000
    url: https://us-ut-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - the-ashh
  - name: Silky.Network - ae
    maxResponseTime: 120000
    url:  https://ae-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - ae-2
    maxResponseTime: 120000
    url:  https://ae-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - ae-3
    maxResponseTime: 120000
    url:  https://ae-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - au
    maxResponseTime: 120000
    url:  https://au-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - au-2
    maxResponseTime: 120000
    url:  https://au-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - br-3
    maxResponseTime: 120000
    url:  https://br-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - br-4
    maxResponseTime: 120000
    url:  https://br-4-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - ca-2
    maxResponseTime: 120000
    url:  https://ca-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - ca-3
    maxResponseTime: 120000
    url:  https://ca-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - ch
    maxResponseTime: 120000
    url:  https://ch-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - cl-2
    maxResponseTime: 120000
    url:  https://cl-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - fr-2
    maxResponseTime: 120000
    url:  https://fr-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - fr-3
    maxResponseTime: 120000
    url:  https://fr-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - de-5
    maxResponseTime: 120000
    url:  https://de-5-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - de-6
    maxResponseTime: 120000
    url:  https://de-6-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - es-3
    maxResponseTime: 120000
    url:  https://es-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - il
    maxResponseTime: 120000
    url:  https://il-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - in-4
    maxResponseTime: 120000
    url:  https://in-4-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - in-5
    maxResponseTime: 120000
    url:  https://in-5-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - in-6
    maxResponseTime: 120000
    url:  https://in-6-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - in-7
    maxResponseTime: 120000
    url:  https://in-7-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - it
    maxResponseTime: 120000
    url:  https://it-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - jp
    maxResponseTime: 120000
    url:  https://jp-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - jp-2
    maxResponseTime: 120000
    url:  https://jp-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - kr-2
    maxResponseTime: 120000
    url:  https://kr-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - kr-3
    maxResponseTime: 120000
    url:  https://kr-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - mx
    maxResponseTime: 120000
    url:  https://mx-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - mx-2
    maxResponseTime: 120000
    url:  https://mx-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - nl
    maxResponseTime: 120000
    url:  https://nl-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - sa
    maxResponseTime: 120000
    url:  https://sa-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - se
    maxResponseTime: 120000
    url:  https://se-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - uk
    maxResponseTime: 120000
    url:  https://uk-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - uk-2
    maxResponseTime: 120000
    url:  https://uk-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - uk-3
    maxResponseTime: 120000
    url:  https://uk-3-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - us-az
    maxResponseTime: 120000
    url:  https://us-az-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - us-az-2
    maxResponseTime: 120000
    url:  https://us-az-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - us-ca
    maxResponseTime: 120000
    url:  https://us-ca-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - us-mi-2
    url:  https://us-mi-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - us-va-2
    maxResponseTime: 120000
    url:  https://us-va-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz
  - name: Silky.Network - za
    maxResponseTime: 120000
    url:  https://za-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - a0xz


# Theming of the statuspage
status-website:
  baseUrl: /
  cname: uptimes.chaotic.cx
  introMessage: This is the status page of Chaotic-AUR which shows current uptime status and historic data 🕵🏻‍♀️
  introTitle: Want to know which mirrors are up?
  logoUrl: https://avatars.githubusercontent.com/u/66071775?s=400&u=99bc0536e7e77fe3e58839996600848f2d930ed5&v=4
  name: Chaotic-AUR Uptimes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://aur.chaotic.cx
  theme: night
  singleCommit: true

# Configuration of the bots commits
commitMessages:
  commitAuthorName: "Chaotic-AUR Uptime Bot"
  commitAuthorEmail: "upptime@chaotic.cx"

# Recommended for GitHub API to work
user-agent: chaotic-aur

workflowSchedule:
  uptime: "0 0 1 1 *"
