# Basic setup
owner: chaotic-aur
repo: chaotic-uptimes
assignees:
  - dr460nf1r3
  - JustTNE

# Our mirrors
sites:
  - name: Homepage
    url: https://aur.chaotic.cx
  - name: The router
    url: https://geo-mirror.chaotic.cx
  - name: cdn (Cloudflare R2)
    url: https://cdn-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
  - name: bg (Sudoman)
    url: https://shantitribe.eu
    assignees:
      - thotypous
  - name: br (UFSCar Alcateia)
    url: mirror.ufscar.br
    assignees:
      - thotypous
  - name: br-2 (Alisson)
    url: br-mirror.amanoteam.com
    assignees:
      - alissonlauffer
  - name: ca (freebird54)
    url: https://birdrepo.ddns.net
  - name: cdn-cn (Aliyun)
    url: https://cdn-cn-mirror.chaotic.cx/
  - name: cl (jkcgs)
    url: https://mirror.owo.cl
    assignees:
      - jkcgs
  - name: de-2 (Bangl)
    url: https://chaotic.bangl.de
  - name: de-3 (itsTyrion)
    url: https://v.itstyrion.de
    assignees:
      - itsTyrion
  - name: de-4 (redglobuli)
    url: https://chaotic.pl4ygr0und.de
    assignees:
      - redglobuli
  - name: es (JKA Network)
    url: https://repo.jkanetwork.com
  - name: es-2 (Ícar)
    url: https://chaotic.icarns.xyz
    assignees:
      - juxuanu
  - name: es-4 (Ícar)
    url: https://chaotic-2.icarns.xyz
    assignees:
      - juxuanu
  - name: fr (Snowy)
    url: https://saturn.dedyn.io
    assignees:
      - Gontier-Julien
  - name: gr (vmmaniac)
    url: https://mirrors.sytes.net
    assignees:
      - vmmaniac
  - name: in (Naman)
    url: https://in-mirror.garudalinux.org
    assignees:
      - Namanlp
  - name: in-2 (Albony)
    url: https://mirror.albony.xyz
    assignees:
      - Albonycal
  - name: kr (silent-heigou)
    url: https://mirror.heigou.pe.kr
    assignees:
      - silent-heigou
  - name: secret (Garuda)
    url: https://builds.garudalinux.org
  - name: sg (Freedif)
    url: https://mirror.freedif.org
    assignees:
      - KaribuTW
  - name: us-fl (Alisson)
    url: https://us-fl-mirror.amanoteam.com
    assignees:
      - alissonlauffer
  - name: us-mi (Technetium1)
    url: https://chaoticmirror.com
    assignees:
      - Technetium1
  - name: us-ny (Zoe)
    url: https://us-ny-mirror.garudalinux.org
    assignees:
      - zoeruda
  - name: us-tx (xstefen)
    url: https://chaotic.xstefen.dev
    assignees:
      - xstefen
  - name: us-ut (Ash)
    url: https://mirror.theash.xyz
    assignees:
      - the-ashh
  - name: Silky.Network - ae
    url: https://dxb-ae-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - ae-2
    url: https://dxb1-ae-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - ae-3
    url: https://auh-ae-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - au
    url: https://syd-au-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - au-2
    url: https://mel-au-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - br-3
    url: https://vcp-br-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - br-4
    url: https://gru-br-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - ca-2
    url: https://yyz-ca-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - ca-3
    url: https://yul-ca-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - ch
    url: https://zrh-ch-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - cl-2
    url: https://scl-cl-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - fr-2
    url: https://cdg-fr-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - fr-3
    url: https://mrs-fr-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - de-5
    url: https://fra-de-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - de-6
    url: https://fra1-de-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - es-3
    url: https://mad-es-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - il
    url: https://jrs-il-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - in-4
    url: https://bom-in-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - in-5
    url: https://bom1-in-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - in-6
    url: https://hyd-in-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - in-7
    url: https://hyd1-in-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - it
    url: https://mxp-it-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - jp
    url: https://nrt-jp-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - jp-2
    url: https://itm-jp-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - kr-2
    url: https://icn-kr-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - kr-3
    url: https://icn-kr-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - mx
    url: https://qro-mx-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - mx-2
    url: https://mex-mx-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - nl
    url: https://ams-nl-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - sa
    url: https://jed-sa-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - se
    url: https://arn-se-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - uk
    url: https://lhr-uk-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - uk-2
    url: https://man-uk-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - uk-3
    url: https://cwl-uk-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - us-az
    url: https://phx-us-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - us-az-2
    url: https://phx1-us-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - us-ca
    url: https://sjc-us-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - us-mi-2
    url: https://ord-us-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - us-va-2
    url: https://iad-us-mirror.silky.network
    assignees:
      - a0xz
  - name: Silky.Network - za
    url: https://jnb-za-mirror.silky.network
    assignees:
      - a0xz

# Theming of the statuspage
status-website:
  baseUrl: /
  cname: uptimes.chaotic.cx
  introMessage: This is the status page of Chaotic-AUR which shows current uptime status and historic data 🕵🏻‍♀️
  introTitle: Want to know which mirrors are up?
  logoUrl: https://avatars.githubusercontent.com/u/66071775?s=400&u=99bc0536e7e77fe3e58839996600848f2d930ed5&v=4
  name: Chaotic-AUR Uptimes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://aur.chaotic.cx
  theme: night
  singleCommit: true

# Configuration of the bots commits
commitMessages:
  commitAuthorName: "Chaotic Temeraire"
  commitAuthorEmail: "actions@chaotic.cx"

# Recommended for GitHub API to work
user-agent: chaotic-aur

workflowSchedule:
  uptime: "0 0 1 1 *"
